export default {
  WOW_TOKEN_NAMESPACE: 'wowToken',
  WOW_TOKEN_FAILURE: 'WOW_TOKEN_FAILURE',
  WOW_TOKEN_INITIALIZATION: 'WOW_TOKEN_INITIALIZATION',
  WOW_TOKEN_INFORMATION: 'INFORMATION',
  WOW_TOKEN_REFRESH: 'WOW_TOKEN_REFRESH',
  WOW_TOKEN_REQUEST: 'WOW_TOKEN_REQUEST',
  WOW_TOKEN_SUCCESS: 'WOW_TOKEN_SUCCESS',
};
