export default {
  WOW_TOKEN_INITIALIZATION: 'WOW_TOKEN_INITIALIZATION',
  WOW_TOKEN_REQUEST: 'WOW_TOKEN_REQUEST',
  WOW_TOKEN_SUCCESS: 'WOW_TOKEN_SUCCESS',
  WOW_TOKEN_FAILURE: 'WOW_TOKEN_FAILURE',
};
